In [27]:
#Code for calculating single scenario with 24 hours
import cvxpy as cp

x = cp.Variable(10, boolean = True) # vector variable

constraints = []
constraints.append (4*x[0]+x[1]+5*x[2]+4*x[3]+3*x[4]+2*x [5]+3*x [6] +x[7]+2*x [8] +6*x [9]<=24)
obj_func= 0.456+.06*x[0]+0.02*x[1]+0.07*x[2]+0.05*x[3]+0.05*x[4]+0.01*x[5]+0.04*x[6]+0.02*x[7]+0.01*x[8]+0.07*x[9]

problem = cp.Problem (cp.Maximize(obj_func), constraints)
#problem.solve(verbose = True)
#problem.solve(solver=cp.CVXOPT, verbose = True)
problem.solve(solver=cp.GUROBI, verbose = True)

                                     CVXPY                                     
                                     v1.5.3                                    
(CVXPY) Nov 25 10:08:40 PM: Your problem has 10 variables, 1 constraints, and 0 parameters.
(CVXPY) Nov 25 10:08:40 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Nov 25 10:08:40 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Nov 25 10:08:40 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
(CVXPY) Nov 25 10:08:40 PM: Your problem is compiled with the CPP canonicalization backend.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Nov 25 10:08:40 PM: Compiling problem (target solver=GUROBI).
(C

np.float64(0.7960000000000003)

In [28]:
#Code for calculating all scenarios with different times allotted
import cvxpy as cp
x = cp.Variable(10, boolean = True) # vector variable
constraints = []
constraints.append (4*x[0]+x[1]+5*x[2]+4*x[3]+3*x[4]+2*x [5]+3*x [6] +x[7]+2*x [8] +6*x [9]<=24)
obj_func24= 0.456+.06*x[0]+0.02*x[1]+0.07*x[2]+0.05*x[3]+0.05*x[4]+0.01*x[5]+0.04*x[6]+0.02*x[7]+0.01*x[8]+0.07*x[9]
problem = cp.Problem (cp.Maximize(obj_func24), constraints)
problem.solve(solver=cp.GUROBI, verbose = False)
print("Assignments completed in 24 hrs")
print(x.value)
x = cp.Variable(10, boolean = True) # vector variable
constraints = []
constraints.append (4*x[0]+x[1]+5*x[2]+4*x[3]+3*x[4]+2*x [5]+3*x [6] +x[7]+2*x [8] +6*x [9]<=26)
obj_func26= 0.456+.06*x[0]+0.02*x[1]+0.07*x[2]+0.05*x[3]+0.05*x[4]+0.01*x[5]+0.04*x[6]+0.02*x[7]+0.01*x[8]+0.07*x[9]
problem = cp.Problem (cp.Maximize(obj_func26), constraints)
problem.solve(solver=cp.GUROBI, verbose = False)
print("Assignments completed in 26 hrs")
print(x.value)
x = cp.Variable(10, boolean = True) # vector variable
constraints = []
constraints.append (4*x[0]+x[1]+5*x[2]+4*x[3]+3*x[4]+2*x [5]+3*x [6] +x[7]+2*x [8] +6*x [9]<=28)
obj_func28= 0.456+.06*x[0]+0.02*x[1]+0.07*x[2]+0.05*x[3]+0.05*x[4]+0.01*x[5]+0.04*x[6]+0.02*x[7]+0.01*x[8]+0.07*x[9]
problem = cp.Problem (cp.Maximize(obj_func28), constraints)
problem.solve(solver=cp.GUROBI, verbose = False)
print("Assignments completed in 28 hrs")
print(x.value)
x = cp.Variable(10, boolean = True) # vector variable
constraints = []
constraints.append (4*x[0]+x[1]+5*x[2]+4*x[3]+3*x[4]+2*x [5]+3*x [6] +x[7]+2*x [8] +6*x [9]<=30)
obj_func30= 0.456+.06*x[0]+0.02*x[1]+0.07*x[2]+0.05*x[3]+0.05*x[4]+0.01*x[5]+0.04*x[6]+0.02*x[7]+0.01*x[8]+0.07*x[9]
problem = cp.Problem (cp.Maximize(obj_func30), constraints)
problem.solve(solver=cp.GUROBI, verbose = False)
print("Assignments completed in 30 hrs")
print(x.value)
x = cp.Variable(10, boolean = True) # vector variable
constraints = []
constraints.append (4*x[0]+x[1]+5*x[2]+4*x[3]+3*x[4]+2*x [5]+3*x [6] +x[7]+2*x [8] +6*x [9]<=31)
obj_func31= 0.456+.06*x[0]+0.02*x[1]+0.07*x[2]+0.05*x[3]+0.05*x[4]+0.01*x[5]+0.04*x[6]+0.02*x[7]+0.01*x[8]+0.07*x[9]
problem = cp.Problem (cp.Maximize(obj_func31), constraints)
problem.solve(solver=cp.GUROBI, verbose = False)
print("Assignments completed in 31 hrs")
print(x.value)
print("grades by hours =")
print(obj_func24.value)
print(obj_func26.value)
print(obj_func28.value)
print(obj_func30.value)
print(obj_func31.value)

Assignments completed in 24 hrs
[1. 1. 1. 1. 1. 0. 0. 1. 0. 1.]
Assignments completed in 26 hrs
[1. 0. 1. 1. 1. 0. 1. 1. 0. 1.]
Assignments completed in 28 hrs
[1. 1. 1. 1. 1. 0. 1. 1. 0. 1.]
Assignments completed in 30 hrs
[1. 1. 1. 1. 1. 1. 1. 1. 0. 1.]
Assignments completed in 31 hrs
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
grades by hours =
0.7960000000000003
0.8160000000000003
0.8360000000000003
0.8460000000000003
0.8560000000000003
